### ISSUE TITLE
binarize4moses2.perl: No such file or directory

### ISSUE THREAD

**Issue by takkarparas** [artetxem/monoses#16]
I am getting this error while making phrase tables.
I tried resolving this error by installing cmph2.0.2 and xmlrpc-c-1.39.12 but couldn't make it.
![Error](https://user-images.githubusercontent.com/41841853/88473915-da5be480-ced6-11ea-8cef-4e34f7704a0f.jpg)

**Comment by meeps123** [comment]
Hello! I also faced this error sometime back. I was also working on an Ubuntu system. What the error means is that you are lacking `moses2` binaries. 

I solved it by downloading the compiled `moses` binaries for Ubuntu 17.04 from [here](http://www.statmt.org/moses/RELEASE-4.0/binaries/). After I unzipped the `ubuntu-17.04.tgz`, I moved the compiled binaries into their corresponding folders in `third-party/moses`.

FYI, I did this because I had issues building `moses` and `moses2` using the `bjam` command. 

Fortunately, `monoses` still works even if you put the binaries in like that.

**Comment by shefs0709** [comment]
Hello...
I was facing the same error but somehow manage to solve this errror...
 After running for 2 days and generating output for all the 7 steps, currently, I am facing bucket full  error.
![IMG-20200731-WA0014](https://user-images.githubusercontent.com/44344241/89059643-2e574500-d37f-11ea-8c5c-b7271d36b244.jpg)
![IMG-20200731-WA0015](https://user-images.githubusercontent.com/44344241/89059706-4af37d00-d37f-11ea-83d6-303c1d0d7ac8.jpg)

Your help will b appriciated ...
Thank u..

**Comment by takkarparas** [comment]
@meeps123 Thanks for your solution it is working and my error is resolved.

**Comment by takkarparas** [comment]
@shefs0709 I think you should make a new issue thread for this error.
I have to close this issue thread.
